on:
  push:
    tags:
      - 'v[0-9]+*'

env:
  IMAGE_NAME: repo-app

jobs:
  docker:
    name: Make image
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        run: docker buildx create --use

      - name: Debug Docker Buildx
        run: docker buildx version

      - name: Make image
        run: |
          docker buildx build --platform linux/amd64 \
            --tag repo.nqws.ru/merch-tracker/repo-app:latest \
            --push .
