on:
  push:
    tags:
      - 'v[0-9]+*'

env:
  IMAGE_NAME: repo-app

jobs:
  docker:
    name: Make image
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login repo.nqws.ru -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Make image
        run: |
          docker buildx build --platform linux/amd64 \
            --tag repo.nqws.ru/merch-tracker/repo-app:latest \
            --push .
